-- Custom migration: Grants for hunt_channel_credits table
-- This file contains SQL that is NOT auto-generated by Drizzle
-- Related to Drizzle migration: 0005_living_ultimo.sql

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."hunt_channel_credits" TO "authenticated", "service_role";